### ISSUE TITLE
Update php version in V2 composer.json

### ISSUE THREAD

**Issue by zerai** [openemr/oe-module-faxsms#12]
https://github.com/openemr/oe-module-faxsms/blob/d23f3c160f1423c23c1896f1fec5a6e75d9e1c5f/composer.json#L24

PHP 7.1 is not supported form last openemr version.

**Comment by sjpadgett** [comment]
Technically true but, module loads on 7.2 or runs fine on 7.1 but will change my next PR. thanks.

**Comment by sjpadgett** [comment]
done, thanks for heads up.
